apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-https-config
  namespace: users-app
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    http {
        server {
            listen 80;
            server_name myusersapp.duckdns.org;
            return 301 https://$server_name$request_uri;
        }
        
        server {
            listen 443 ssl;
            server_name myusersapp.duckdns.org;
            
            ssl_certificate /etc/nginx/ssl/tls.crt;
            ssl_certificate_key /etc/nginx/ssl/tls.key;
            
            # Frontend
            location / {
                proxy_pass http://users-frontend:80;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
            
            # Backend API
            location /api/ {
                proxy_pass http://users-backend:80/api/;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
            }
        }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-https-proxy
  namespace: users-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-https-proxy
  template:
    metadata:
      labels:
        app: nginx-https-proxy
    spec:
      containers:
      - name: nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        - containerPort: 443
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
        - name: tls-certs
          mountPath: /etc/nginx/ssl
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-https-config
      - name: tls-certs
        secret:
          secretName: myusersapp-tls
