apiVersion: batch/v1
kind: Job
metadata:
  name: django-migrations
  namespace: users-app
spec:
  template:
    spec:
      containers:
      - name: django-migrate
        image: 211865220371.dkr.ecr.us-east-1.amazonaws.com/users-backend:latest
        command: ["python", "manage.py", "migrate"]
        env:
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: DB_PASSWORD
      restartPolicy: Never
  backoffLimit: 3
